### ISSUE TITLE
Hangs then error on load

### ISSUE THREAD

**Issue by azukaar** [hylian-modding/ModLoader64-GUI#26]
Hello
The clients hangs on NetworkEngine.Client - Starting up NetworkEngine.Client...
But then flashes an error, except the window closes itself and there's no time to read the error.
Any way i can retrieve it ? Last-report.txt is empty as well

**Comment by LegendaryRed98** [comment]
Has this been solved? Because I'm having the same issue.

**Comment by denoflionsx** [comment]
More than likely you're trying to load ModLoader with no Online mod enabled while also not being in offline mode. Without a mod like Ocarina of Time Online, Majora's Mask Online, etc, enabled it doesn't know what you're intending to connect to.

**Comment by denoflionsx** [comment]
You'll also have far better luck getting help on [discord](https://discord.gg/modloader64). We don't have anyone watching github issues for this sort of thing.
