### ISSUE TITLE
Not Closing Properly (Linux)

### ISSUE THREAD

**Issue by luke512** [hylian-modding/ModLoader64-GUI#9]
Every time I close the game window, this error message appears.
`Unhandled Error`
`TypeError: Error processing argument at index 1, conversion failure from undefined
    at Object.showErrorBox (electron/js2c/browser_init.js:994:20)
    at ChildProcess.<anonymous> (/opt/modloader64-gui/resources/src/index.ts:404:11)`

The program will also run forever until I manually end the processes.

**Comment by denoflionsx** [comment]
@TheLensta Does 5cb3e399e3b53ea8f16c434eab628c179724fdbc fix this?

**Comment by TheLensta** [comment]
Yes, same issue
